-- MySQL Script generated by MySQL Workbench
-- 07/26/16 15:48:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema cardfactory
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cardfactory
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cardfactory` DEFAULT CHARACTER SET utf8 ;
USE `cardfactory` ;

-- -----------------------------------------------------
-- Table `cardfactory`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardfactory`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(256) NULL,
  `updatedDate` TIMESTAMP NULL,
  `createdDate` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nickname_UNIQUE` (`nickname` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardfactory`.`card_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardfactory`.`card_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `defaultHtml` TEXT NULL,
  `thumbnailHtml` TEXT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cardfactory`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cardfactory`.`card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `html` TEXT NULL,
  `hitsCount` INT NULL,
  `likesCount` INT NULL,
  `updatedDate` TIMESTAMP NULL,
  `createdDate` TIMESTAMP NULL,
  `userId` INT NULL,
  `cardTypeId` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `userId_idx` (`userId` ASC),
  INDEX `cardTypeId_idx` (`cardTypeId` ASC),
  CONSTRAINT `userId`
    FOREIGN KEY (`userId`)
    REFERENCES `cardfactory`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cardTypeId`
    FOREIGN KEY (`cardTypeId`)
    REFERENCES `cardfactory`.`card_type` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
